function fxGitAsOwner()
{
  if [ -z "$1" ]; then
    local PROJECT_DIR=$(pwd)
  else
    local PROJECT_DIR=$1
  fi

  ## the top-level dir often belongs to root, but the deploy key and the repo data
  ## belong to the user owning .git (which is a file on submodules and worktrees)
  local OWNER_PROBE=${PROJECT_DIR%/}/.git
  if [ ! -e "${OWNER_PROBE}" ]; then
    OWNER_PROBE=${PROJECT_DIR}
  fi

  local PROJECT_DIR_OWNER=$(fxGetFileOwner ${OWNER_PROBE})

  if [ "$(whoami)" = "$PROJECT_DIR_OWNER" ]; then
    git -C "${PROJECT_DIR}" "${@:2}"
  else
    sudo -u $PROJECT_DIR_OWNER -H  git -C "${PROJECT_DIR}" "${@:2}"
  fi
}


function fxGitPushAndShallow()
{
  local PROJECT_DIR=${1%/}

  if [ -z "${PROJECT_DIR}" ] || [ ! -d "${PROJECT_DIR}" ]; then
    fxCatastrophicError "fxGitPushAndShallow: ##${1}## doesn't exist"
  fi

  ## it's a file, not a directory, on submodules and worktrees
  if [ ! -e "${PROJECT_DIR}/.git" ]; then
    fxCatastrophicError "fxGitPushAndShallow: ##${PROJECT_DIR}## is not a git repository"
  fi

  fxTitle "☁️ Git pushing..."
  fxGitAsOwner "${PROJECT_DIR}" push
  local GIT_PUSH_RESULT=$?

  fxTitle "✂️ Re-shallowing the repo..."
  ## autogenerated commits pile the local history up forever. Never re-shallow on a failed
  ## push, or we would prune away a commit which exists nowhere else!
  if [ "${GIT_PUSH_RESULT}" != 0 ]; then

    fxWarning "The push FAILED: keeping the local history"
    return "${GIT_PUSH_RESULT}"
  fi

  local GIT_BRANCH=$(fxGitAsOwner "${PROJECT_DIR}" rev-parse --abbrev-ref HEAD)

  ## the fetch only moves the boundary: it's the gc which actually reclaims the space,
  ## and the reflog would keep the orphaned objects reachable
  fxGitAsOwner "${PROJECT_DIR}" fetch --depth=1 origin "${GIT_BRANCH}"
  fxGitAsOwner "${PROJECT_DIR}" reflog expire --expire=now --all
  fxGitAsOwner "${PROJECT_DIR}" gc --prune=now --quiet

  fxOK "$(fxGitAsOwner "${PROJECT_DIR}" rev-list --count HEAD) commit(s) left, $(du -sh "${PROJECT_DIR}/.git" | cut -f1) on disk"
}


function fxGitPullAndShallow()
{
  local PROJECT_DIR=${1%/}

  if [ -z "${PROJECT_DIR}" ] || [ ! -d "${PROJECT_DIR}" ]; then
    fxCatastrophicError "fxGitPullAndShallow: ##${1}## doesn't exist"
  fi

  ## it's a file, not a directory, on submodules and worktrees
  if [ ! -e "${PROJECT_DIR}/.git" ]; then
    fxCatastrophicError "fxGitPullAndShallow: ##${PROJECT_DIR}## is not a git repository"
  fi

  fxTitle "⬇️ Getting the latest revision..."
  local GIT_BRANCH=$(fxGitAsOwner "${PROJECT_DIR}" rev-parse --abbrev-ref HEAD)

  ## fetch+reset instead of pull: --depth=1 always re-shallows, moving the boundary to the
  ## newly-fetched tip, so only the very last revision is available locally. It also never
  ## needs a merge base, which a depth=1 repo wouldn't have on a forced update
  fxGitAsOwner "${PROJECT_DIR}" fetch --depth=1 origin "${GIT_BRANCH}"
  local GIT_FETCH_RESULT=$?

  if [ "${GIT_FETCH_RESULT}" != 0 ]; then

    fxWarning "The fetch FAILED: keeping the current revision"
    return "${GIT_FETCH_RESULT}"
  fi

  ## this is a deploy-only copy: any local change must be discarded
  fxGitAsOwner "${PROJECT_DIR}" reset --hard FETCH_HEAD

  fxTitle "✂️ Re-shallowing the repo..."
  ## the fetch only moves the boundary: it's the gc which actually reclaims the space,
  ## and the reflog would keep the orphaned objects reachable
  fxGitAsOwner "${PROJECT_DIR}" reflog expire --expire=now --all
  fxGitAsOwner "${PROJECT_DIR}" gc --prune=now --quiet

  fxOK "$(fxGitAsOwner "${PROJECT_DIR}" rev-list --count HEAD) commit(s) left, $(du -sh "${PROJECT_DIR}/.git" | cut -f1) on disk"
}


function fxGitCheckForUpdate()
{
  if [ -z "$1" ]; then
    local PROJECT_DIR=$(pwd)
  else
    local PROJECT_DIR=$1
  fi

  local SILENT_MODE=$2

  if [ -z "$SILENT_MODE" ]; then
   fxTitle "🔎 Checking if a new git revision is available..."
  fi

  fxGitAsOwner "${PROJECT_DIR}" fetch

  local LOCAL_REV=$(fxGitAsOwner "${PROJECT_DIR}" rev-parse @)

  if [ -z "$SILENT_MODE" ]; then
   fxInfo "Local rev. : ##${LOCAL_REV}##"
  fi

  local REMOTE_REV=$(fxGitAsOwner "${PROJECT_DIR}" rev-parse @{u})

  if [ -z "$SILENT_MODE" ]; then
   fxInfo "Remote rev.: ##${REMOTE_REV}##"
  fi

  local BASE_REV=$(fxGitAsOwner "${PROJECT_DIR}" merge-base @ @{u})

  if [ "$LOCAL_REV" = "$REMOTE_REV" ]; then

    if [ -z "$SILENT_MODE" ]; then
      fxOK "Up-to-date"
    fi

    return 0
  fi


  if [ "$LOCAL_REV" = "$BASE_REV" ]; then

    if [ -z "$SILENT_MODE" ]; then
      fxWarning "Need to pull"
    fi

    return 1
  fi


  if [ "$REMOTE_REV" = "$BASE_REV" ]; then

    if [ -z "$SILENT_MODE" ]; then
      fxWarning "Need to push"
    fi

    return 2
  fi


  if [ -z "$SILENT_MODE" ]; then
      fxWarning "Branch diverged"
  fi

  return 3
}
